# -*- coding: utf-8 -*-
"""adv_train_VisionTransformer_BloodMNIST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/153SVKZx9yFPa7vTC2qRY4m0ocFbo3AUB

https://medium.com/correll-lab/building-a-vision-transformer-model-from-scratch-a3054f707cc6
"""

from google.colab import drive
drive.mount('/content/drive')

import torch
import torch.nn as nn
import torchvision.transforms as T
from torch.optim import Adam
from torch.utils.data import DataLoader
from torchvision.datasets.mnist import MNIST
import numpy as np

from torch.utils.data import Dataset, DataLoader

import os
import cv2

"""# Patch Embeddings"""

class PatchEmbedding(nn.Module):
  def __init__(self, d_model, img_size, patch_size, n_channels):
    super().__init__()

    self.d_model = d_model # Dimensionality of Model
    self.img_size = img_size # Image Size
    self.patch_size = patch_size # Patch Size
    self.n_channels = n_channels # Number of Channels

    self.linear_project = nn.Conv2d(self.n_channels, self.d_model, kernel_size=self.patch_size, stride=self.patch_size)

  # B: Batch Size
  # C: Image Channels
  # H: Image Height
  # W: Image Width
  # P_col: Patch Column
  # P_row: Patch Row
  def forward(self, x):
    x = self.linear_project(x) # (B, C, H, W) -> (B, d_model, P_col, P_row)

    x = x.flatten(2) # (B, d_model, P_col, P_row) -> (B, d_model, P)

    x = x.transpose(-2, -1) # (B, d_model, P) -> (B, P, d_model)

    return x

"""# Class Token and Positional Encoding"""

class PositionalEncoding(nn.Module):
  def __init__(self, d_model, max_seq_length):
    super().__init__()

    self.cls_token = nn.Parameter(torch.randn(1, 1, d_model)) # Classification Token

    # Creating positional encoding
    pe = torch.zeros(max_seq_length, d_model)

    for pos in range(max_seq_length):
      for i in range(d_model):
        if i % 2 == 0:
          pe[pos][i] = np.sin(pos/(10000 ** (i/d_model)))
        else:
          pe[pos][i] = np.cos(pos/(10000 ** ((i-1)/d_model)))

    self.register_buffer('pe', pe.unsqueeze(0))

  def forward(self, x):
    # Expand to have class token for every image in batch
    tokens_batch = self.cls_token.expand(x.size()[0], -1, -1)

    # Adding class tokens to the beginning of each embedding
    x = torch.cat((tokens_batch,x), dim=1)

    # Add positional encoding to embeddings
    x = x + self.pe

    return x

"""# Multi-Head Attention"""

class AttentionHead(nn.Module):
  def __init__(self, d_model, head_size):
    super().__init__()
    self.head_size = head_size

    self.query = nn.Linear(d_model, head_size)
    self.key = nn.Linear(d_model, head_size)
    self.value = nn.Linear(d_model, head_size)

  def forward(self, x):
    # Obtaining Queries, Keys, and Values
    Q = self.query(x)
    K = self.key(x)
    V = self.value(x)

    # Dot Product of Queries and Keys
    attention = Q @ K.transpose(-2,-1)

    # Scaling
    attention = attention / (self.head_size ** 0.5)

    attention = torch.softmax(attention, dim=-1)

    attention = attention @ V

    return attention

class MultiHeadAttention(nn.Module):
  def __init__(self, d_model, n_heads):
    super().__init__()
    self.head_size = d_model // n_heads

    self.W_o = nn.Linear(d_model, d_model)

    self.heads = nn.ModuleList([AttentionHead(d_model, self.head_size) for _ in range(n_heads)])

  def forward(self, x):
    # Combine attention heads
    out = torch.cat([head(x) for head in self.heads], dim=-1)

    out = self.W_o(out)

    return out

"""# Transformer Encoder"""

class TransformerEncoder(nn.Module):
  def __init__(self, d_model, n_heads, r_mlp=4):
    super().__init__()
    self.d_model = d_model
    self.n_heads = n_heads

    # Sub-Layer 1 Normalization
    self.ln1 = nn.LayerNorm(d_model)

    # Multi-Head Attention
    self.mha = MultiHeadAttention(d_model, n_heads)

    # Sub-Layer 2 Normalization
    self.ln2 = nn.LayerNorm(d_model)

    # Multilayer Perception
    self.mlp = nn.Sequential(
        nn.Linear(d_model, d_model*r_mlp),
        nn.GELU(),
        nn.Linear(d_model*r_mlp, d_model)
    )

  def forward(self, x):
    # Residual Connection After Sub-Layer 1
    out = x + self.mha(self.ln1(x))

    # Residual Connection After Sub-Layer 2
    out = out + self.mlp(self.ln2(out))

    return out

"""# Vision Transformer Model"""

class VisionTransformer(nn.Module):
  def __init__(self, d_model, n_classes, img_size, patch_size, n_channels, n_heads, n_layers):
    super().__init__()

    assert img_size[0] % patch_size[0] == 0 and img_size[1] % patch_size[1] == 0, "img_size dimensions must be divisible by patch_size dimensions"
    assert d_model % n_heads == 0, "d_model must be divisible by n_heads"

    self.d_model = d_model # Dimensionality of model
    self.n_classes = n_classes # Number of classes
    self.img_size = img_size # Image size
    self.patch_size = patch_size # Patch size
    self.n_channels = n_channels # Number of channels
    self.n_heads = n_heads # Number of attention heads

    self.n_patches = (self.img_size[0] * self.img_size[1]) // (self.patch_size[0] * self.patch_size[1])
    self.max_seq_length = self.n_patches + 1

    self.patch_embedding = PatchEmbedding(self.d_model, self.img_size, self.patch_size, self.n_channels)
    self.positional_encoding = PositionalEncoding( self.d_model, self.max_seq_length)
    self.transformer_encoder = nn.Sequential(*[TransformerEncoder( self.d_model, self.n_heads) for _ in range(n_layers)])

    # Classification MLP
    self.classifier = nn.Sequential(
        nn.Linear(self.d_model, self.n_classes),
        nn.Softmax(dim=-1)
    )

  def forward(self, images):
        x = self.patch_embedding(images)
        #print("Shape after patch embedding:", x.shape)  # Check shape

        x = self.positional_encoding(x)
        #print("Shape after positional encoding:", x.shape)  # Check shape

        x = self.transformer_encoder(x)
        #print("Shape after transformer encoder:", x.shape)  # Check shape

        x = self.classifier(x[:, 0])
        #print("Shape after classifier:", x.shape)  # Check shape

        return x

"""# Training Parameters"""

d_model = 9
n_classes = 8
img_size = (28, 28)
patch_size = (14,14)
n_channels = 3
n_heads = 3
n_layers = 3
batch_size = 128
epochs = 100
alpha = 0.005

"""# Load MNIST Dataset"""

pip install medmnist

import medmnist
from medmnist import DermaMNIST
from torchvision import transforms

# Load the dataset (train, val, test split)
data_flag = "dermamnist"  # Specify the dataset, e.g., pathmnist, chestmnist, etc.
download = True

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[.5], std=[.5])
])

# Initialize datasets
train_dataset = medmnist.BloodMNIST(split='train', transform=transform, download=download)
#val_dataset = medmnist.BreastMNIST(split='val', transform=transform, download=download)
test_dataset = medmnist.BloodMNIST(split='test', transform=transform, download=download)
print(train_dataset)

# Create data loaders
train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)
#val_loader = DataLoader(dataset=val_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=False)

"""# Training"""

count = 0
for i, data in enumerate(train_loader, 0):
    inputs, labels = data
    labels = labels.reshape(-1)
    count = count + 1
    if(count == 3):
      break
    print(count)
    print(inputs)
    print(torch.max(inputs))
    print(inputs.shape)
    print(labels)
    print(labels.shape)



device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device: ", device, f"({torch.cuda.get_device_name(device)})" if torch.cuda.is_available() else "")

transformer = VisionTransformer(d_model, n_classes, img_size, patch_size, n_channels, n_heads, n_layers).to(device)

optimizer = Adam(transformer.parameters(), lr=alpha)
criterion = nn.CrossEntropyLoss()
import time

# Start timing
start_time = time.time()
for epoch in range(epochs):

  training_loss = 0.0
  for i, data in enumerate(train_loader, 0):
    #print("len", len(data))
    inputs, labels = data
    labels = labels.reshape(-1)
    inputs, labels = inputs.to(device), labels.to(device)

    optimizer.zero_grad()

    outputs = transformer(inputs)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()

    training_loss += loss.item()

  print(f'Epoch {epoch + 1}/{epochs} loss: {training_loss  / len(train_loader) :.3f}')

end_time = time.time()

# Compute execution time
execution_time = end_time - start_time
print(f"Execution Time: {execution_time:.2f} seconds in gpu")

def save_model_to_drive(model, filename):
    save_path = f"/content/drive/MyDrive/Research_workarea/{filename}"
    torch.save(model.state_dict(), save_path)
    print(f"Model saved to Google Drive as {save_path}")

from google.colab import drive
drive.mount('/content/drive')

save_model_to_drive(transformer, "advtrain_ViT_breast_28.pth")

"""# Testing"""

import torch
import torch.nn.functional as F
from tqdm import tqdm

# Function to calculate accuracy
def calculate_accuracy(model, data_loader, device):
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels in data_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            labels = labels.reshape(-1)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
    accuracy = 100 * correct / total
    return accuracy

# Evaluate clean accuracy
    clean_accuracy = calculate_accuracy(transformer, test_loader, device)
    print(f"Clean Accuracy: {clean_accuracy:.2f}%")

# FGSM adversarial attack
def fgsm_attack(model, images, labels, epsilon):
    images.requires_grad = True
    outputs = model(images)
    labels = labels.reshape(-1)
    loss = nn.CrossEntropyLoss()(outputs, labels)
    model.zero_grad()
    loss.backward()
    data_grad = images.grad.data
    perturbed_images = images + epsilon * data_grad.sign()
    perturbed_images = torch.clamp(perturbed_images, 0, 1)
    return perturbed_images

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import numpy as np

def visualize_examples(data, perturbed_data, epsilon):
    fig, axs = plt.subplots(1, 2, figsize=(10, 5))
    # Detach the tensor before calling numpy()
    axs[0].imshow(data[0][0].cpu().detach().numpy(), cmap='gray')
    axs[0].set_title("Original Image")
    axs[1].imshow(perturbed_data[0][0].cpu().detach().numpy(), cmap='gray')
    axs[1].set_title(f"Perturbed Image (ε={epsilon})")
    plt.show()

epochs =100
epsilon = 0.2

def train(model, device, train_loader, optimizer, epsilon):
    model.train()
    total_loss = 0
    for data, target in train_loader:
        data, target = data.to(device), target.to(device)

        # Reshape target to be a 1D tensor
        target = target.reshape(-1)  # or target = target.squeeze() if it's a column vector
        #print(target.shape)

        # Create adversarial examples
        perturbed_data = fgsm_attack(model, data, target, epsilon)

        optimizer.zero_grad()
        output_clean = model(data)

        # Calculate loss using the reshaped target
        loss_clean = nn.CrossEntropyLoss()(output_clean, target)

        output_adv = model(perturbed_data)
        loss_adv = nn.CrossEntropyLoss()(output_adv, target)

        loss = loss_clean + loss_adv  # Combined loss for both examples
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)
    return avg_loss

import time

start_time = time.time()
for epoch in range(1, epochs + 1):
    avg_loss = train(transformer, device, train_loader, optimizer, epsilon)
    print(f"Epoch {epoch}/{epochs} - Average Loss: {avg_loss:.4f}")

end_time = time.time()

execution_time = end_time - start_time
print(f"Execution time: {execution_time:.4f} seconds in gpu")

def save_model_to_drive(model, filename):
    save_path = f"/content/drive/MyDrive/Research_workarea/{filename}"
    torch.save(model.state_dict(), save_path)
    print(f"Model saved to Google Drive as {save_path}")





save_model_to_drive(transformer, "advtrain_ViT_blood_28.pth")