# -*- coding: utf-8 -*-
"""VisionTransformer_BloodMNIST_hog+advtraining_tested.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mZTR4Taa4y-tzts9RpON1ugK02HCibne

https://medium.com/correll-lab/building-a-vision-transformer-model-from-scratch-a3054f707cc6
"""

from google.colab import drive
drive.mount('/content/drive')

import torch
import torch.nn as nn
import torchvision.transforms as T
from torch.optim import Adam
from torch.utils.data import DataLoader
from torchvision.datasets.mnist import MNIST
import numpy as np
from torch.utils.data import Dataset, DataLoader
import os
import cv2

"""# Patch Embeddings"""

class PatchEmbedding(nn.Module):
  def __init__(self, d_model, img_size, patch_size, n_channels):
    super().__init__()

    self.d_model = d_model # Dimensionality of Model
    self.img_size = img_size # Image Size
    self.patch_size = patch_size # Patch Size
    self.n_channels = n_channels # Number of Channels

    self.linear_project = nn.Conv2d(self.n_channels, self.d_model, kernel_size=self.patch_size, stride=self.patch_size)

  # B: Batch Size
  # C: Image Channels
  # H: Image Height
  # W: Image Width
  # P_col: Patch Column
  # P_row: Patch Row
  def forward(self, x):
    x = self.linear_project(x) # (B, C, H, W) -> (B, d_model, P_col, P_row)

    x = x.flatten(2) # (B, d_model, P_col, P_row) -> (B, d_model, P)

    x = x.transpose(-2, -1) # (B, d_model, P) -> (B, P, d_model)

    return x

"""# Class Token and Positional Encoding"""

class PositionalEncoding(nn.Module):
  def __init__(self, d_model, max_seq_length):
    super().__init__()

    self.cls_token = nn.Parameter(torch.randn(1, 1, d_model)) # Classification Token

    # Creating positional encoding
    pe = torch.zeros(max_seq_length, d_model)

    for pos in range(max_seq_length):
      for i in range(d_model):
        if i % 2 == 0:
          pe[pos][i] = np.sin(pos/(10000 ** (i/d_model)))
        else:
          pe[pos][i] = np.cos(pos/(10000 ** ((i-1)/d_model)))

    self.register_buffer('pe', pe.unsqueeze(0))

  def forward(self, x):
    # Expand to have class token for every image in batch
    tokens_batch = self.cls_token.expand(x.size()[0], -1, -1)

    # Adding class tokens to the beginning of each embedding
    x = torch.cat((tokens_batch,x), dim=1)

    # Add positional encoding to embeddings
    x = x + self.pe

    return x

"""# Multi-Head Attention"""

class AttentionHead(nn.Module):
  def __init__(self, d_model, head_size):
    super().__init__()
    self.head_size = head_size

    self.query = nn.Linear(d_model, head_size)
    self.key = nn.Linear(d_model, head_size)
    self.value = nn.Linear(d_model, head_size)

  def forward(self, x):
    # Obtaining Queries, Keys, and Values
    Q = self.query(x)
    K = self.key(x)
    V = self.value(x)

    # Dot Product of Queries and Keys
    attention = Q @ K.transpose(-2,-1)

    # Scaling
    attention = attention / (self.head_size ** 0.5)

    attention = torch.softmax(attention, dim=-1)

    attention = attention @ V

    return attention

class MultiHeadAttention(nn.Module):
  def __init__(self, d_model, n_heads):
    super().__init__()
    self.head_size = d_model // n_heads

    self.W_o = nn.Linear(d_model, d_model)

    self.heads = nn.ModuleList([AttentionHead(d_model, self.head_size) for _ in range(n_heads)])

  def forward(self, x):
    # Combine attention heads
    out = torch.cat([head(x) for head in self.heads], dim=-1)

    out = self.W_o(out)

    return out

"""# Transformer Encoder"""

class TransformerEncoder(nn.Module):
  def __init__(self, d_model, n_heads, r_mlp=4):
    super().__init__()
    self.d_model = d_model
    self.n_heads = n_heads

    # Sub-Layer 1 Normalization
    self.ln1 = nn.LayerNorm(d_model)

    # Multi-Head Attention
    self.mha = MultiHeadAttention(d_model, n_heads)

    # Sub-Layer 2 Normalization
    self.ln2 = nn.LayerNorm(d_model)

    # Multilayer Perception
    self.mlp = nn.Sequential(
        nn.Linear(d_model, d_model*r_mlp),
        nn.GELU(),
        nn.Linear(d_model*r_mlp, d_model)
    )

  def forward(self, x):
    # Residual Connection After Sub-Layer 1
    out = x + self.mha(self.ln1(x))

    # Residual Connection After Sub-Layer 2
    out = out + self.mlp(self.ln2(out))

    return out

"""# Vision Transformer Model"""

class VisionTransformer(nn.Module):
  def __init__(self, width, d_model, n_classes, img_size, patch_size, n_channels, n_heads, n_layers,emb_dim):
    super().__init__()

    assert img_size[0] % patch_size[0] == 0 and img_size[1] % patch_size[1] == 0, "img_size dimensions must be divisible by patch_size dimensions"
    assert d_model % n_heads == 0, "d_model must be divisible by n_heads"
    assert width % n_heads == 0, "width must be divisible by n_heads"
    #self.width = width
    self.d_model = d_model # Dimensionality of model
    self.n_classes = n_classes # Number of classes
    self.img_size = img_size # Image size
    self.patch_size = patch_size # Patch size
    self.n_channels = n_channels # Number of channels
    self.n_heads = n_heads # Number of attention heads

    self.n_patches = (self.img_size[0] * self.img_size[1]) // (self.patch_size[0] * self.patch_size[1])
    self.max_seq_length = self.n_patches + 1

    self.patch_embedding = PatchEmbedding(self.d_model, self.img_size, self.patch_size, self.n_channels)
    self.positional_encoding = PositionalEncoding( self.d_model, self.max_seq_length)
    self.transformer_encoder = nn.Sequential(*[TransformerEncoder( self.d_model, self.n_heads) for _ in range(n_layers)])
    # learned proj of image to embed
    self.projection = nn.Parameter(torch.randn(width, emb_dim))
    #self.feature_projector = nn.Linear(128, 32)
    # Classification MLP
    self.classifier = nn.Sequential(
        nn.Linear(29, self.d_model),
        nn.Linear(self.d_model, self.n_classes),
        nn.Softmax(dim=-1)
    )

  def forward(self, images, features_hog, features_adv):
        x = self.patch_embedding(images)
        #print("Shape after patch embedding:", x.shape)  # Check shape

        x = self.positional_encoding(x)
        #print("Shape after positional encoding:", x.shape)  # Check shape

        x = self.transformer_encoder(x)
        #print("Shape after transformer encoder:", x.shape)  # Check shape

        #print("After transformer encoder")
        #print("x", x)
        #print("x.shape", x.shape)
        # Takes Class Tokens
        x = x[:, 0, :]
        #print("After taking class tokens")
        #print("x", x)
        #print("x.shape", x.shape)

        # # joint multimodal embedding
        # if self.projection is not None:
        #     x = x @ self.projection
        # print("After joint multimodal embedding")
        # print("x", x)
        # print("x.shape", x.shape)
        # x = x / torch.norm(x, dim=-1, keepdim=True)
        # print("After normalization")
        # print("x", x)
        # print("x.shape", x.shape)
        #additional_feature = features
        #print("Shape of additional feature:", additional_feature.shape)  # Check shape
        #additional_feature = additional_feature.reshape(1, additional_feature.shape[0])
        #print("Shape after unsqueeze:", additional_feature.shape)  # Check shape
        #additional_feature_proj = self.feature_projector(torch.tensor(additional_feature, dtype=torch.float32, device=device))
        #print("Shape after feature projector:", additional_feature_proj.shape)  # Check shape
        # Concatenate [CLS] token with the additional feature
        combined_features = torch.cat([x, features_hog, features_adv], dim=-1)
        #print("Shape after concatenation:", combined_features.shape)  # Check shape
        x = self.classifier(combined_features)
        #print("Shape after classifier:", x.shape)  # Check shape

        return x

"""# Training Parameters"""

d_model = 9
n_classes = 8
img_size = (28, 28)
patch_size = (14,14)
n_channels = 3
n_heads = 3
n_layers = 3
batch_size = 128
epochs = 100
alpha = 0.005

vit_width = 9
emb_dim = 32

"""# Load MNIST Dataset"""

pip install medmnist

import medmnist
from medmnist import BloodMNIST
from torchvision import transforms

# Load the dataset (train, val, test split)
data_flag = "dermamnist"  # Specify the dataset, e.g., pathmnist, chestmnist, etc.
download = True

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[.5], std=[.5])
])

# Initialize datasets
train_dataset = medmnist.BloodMNIST(split='train', transform=transform, download=download)
test_dataset = medmnist.BloodMNIST(split='test', transform=transform, download=download)

# Create data loaders
train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=False)

print(train_dataset)

"""# Training"""

import torch
import torchvision.transforms as transforms
from torchvision.datasets import ImageFolder
from skimage.feature import hog
from skimage.color import rgb2gray
import numpy as np

# Compute HOG features for each image in the loader
def compute_hog_features(loader):
    hog_features = []
    labels = []
    for images, targets in loader:
        # Convert to NumPy array and process batch
        images_np = images.permute(0, 2, 3, 1).numpy()  # Convert to (batch, H, W, C)
        for img, label in zip(images_np, targets):
            # Remove the channel dimension if it is grayscale
            if img.shape[-1] == 1:  # Grayscale image with shape (H, W, 1)
                gray_img = img.squeeze(-1)  # Remove the channel dimension
            elif img.shape[-1] == 3:  # RGB image with shape (H, W, 3)
                gray_img = rgb2gray(img)  # Convert RGB to grayscale
            else:
                raise ValueError(f"Unexpected image shape: {img.shape}")

            # Compute HOG features
            features = hog(gray_img,
                           orientations=9,
                           pixels_per_cell=(8, 8),
                           cells_per_block=(2, 2),
                           block_norm='L2-Hys',
                           visualize=False)
            hog_features.append(features)
            labels.append(label.item())
    return np.array(hog_features), np.array(labels)

# Calculate HOG features
train_hog_features, train_labels = compute_hog_features(train_loader)
test_hog_features, test_labels = compute_hog_features(test_loader)

#Output results
print(f"Train HOG features shape: {train_hog_features.shape}")
print(f"Test HOG features shape: {test_hog_features.shape}")
print(f"Train labels shape: {train_labels.shape}")
print(f"Test labels shape: {test_labels.shape}")

hog_size = train_hog_features[1].reshape(-1).shape[0]
print(hog_size)

import torch
from torch.utils.data import Dataset, DataLoader
from skimage.feature import hog
from skimage.color import rgb2gray
import numpy as np
feature_projector_hog = nn.Linear(hog_size, 10)
class DermaMNISTWithHOG(Dataset):
    def __init__(self, original_dataset):
        self.original_dataset = original_dataset

    def __len__(self):
        return len(self.original_dataset)

    def __getitem__(self, idx):
        # Get image and label
        image, label = self.original_dataset[idx]

        # Convert image to NumPy array and compute HOG features

        image_np = image.permute(1, 2, 0).numpy()  # Convert to (H, W, C)

        # Remove the channel dimension if it is grayscale
        if image_np.shape[-1] == 1:  # Grayscale image with shape (H, W, 1)
            gray_img = image_np.squeeze(-1)  # Remove the channel dimension
        elif image_np.shape[-1] == 3:  # RGB image with shape (H, W, 3)
            gray_img = rgb2gray(image_np)  # Convert RGB to grayscale
        else:
            raise ValueError(f"Unexpected image shape: {image_np.shape}")

        #gray_img = rgb2gray(image_np)

        hog_features = hog(
            gray_img,
            orientations=9,
            pixels_per_cell=(8, 8),
            cells_per_block=(2, 2),
            block_norm='L2-Hys',
            visualize=False
        )

        # Convert HOG features to a tensor
        hog_features_tensor = torch.tensor(hog_features, dtype=torch.float32)
        hog_features_tensor = feature_projector_hog(hog_features_tensor)
        return image, label, hog_features_tensor


# Wrap original loaders with the new dataset
def create_hog_loaders(trainloader, testloader):
    train_dataset = DermaMNISTWithHOG(train_loader.dataset)
    test_dataset = DermaMNISTWithHOG(test_loader.dataset)

    train_loader_with_hog = DataLoader(train_dataset, batch_size=trainloader.batch_size, shuffle=True)
    test_loader_with_hog = DataLoader(test_dataset, batch_size=testloader.batch_size, shuffle=False)

    return train_loader_with_hog, test_loader_with_hog


# Example: Assuming `trainloader` and `testloader` are already created
train_loader_with_hog, test_loader_with_hog = create_hog_loaders(train_loader, test_loader)

# Test the new loaders
for images, labels, hog_features in train_loader_with_hog:
    print(f"Image batch shape: {images.shape}")

    print(f"Labels batch shape: {labels.shape}")
    print(f"HOG features batch shape: {hog_features.shape}")
    break

class Net(nn.Module):
    def __init__(self, num_classes=8):
        super(Net, self).__init__()

        # Convolutional layers
        self.conv1 = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, stride=1, padding=1)  # Output: (16, 28, 28)
        self.conv2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, stride=1, padding=1)  # Output: (32, 28, 28)

        # Pooling layer
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)  # Reduces size by half: (32, 14, 14)

        # Fully connected layers
        self.fc1 = nn.Linear(32 * 14 * 14, 128)  # 32 channels, 14x14 spatial size
        self.fc2 = nn.Linear(128, num_classes)  # Final output layer

    def forward(self, x):
        x = F.relu(self.conv1(x))  # Apply ReLU after first conv
        x = self.pool(F.relu(self.conv2(x)))  # Apply ReLU and pooling after second conv

        # Flatten the tensor for the fully connected layers
        x = x.view(x.size(0), -1)  # Reshape to (batch_size, 32 * 14 * 14)
         # Fully connected layer 1
        fc1_output = F.relu(self.fc1(x))

        # Fully connected layer 2 (output layer)
        final_output = self.fc2(fc1_output)

        return final_output, fc1_output

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device: ", device, f"({torch.cuda.get_device_name(device)})" if torch.cuda.is_available() else "")

# Load adversarial-trained model
adv_model = Net().to(device)
adv_model.load_state_dict(torch.load("/content/drive/MyDrive/Research_workarea/advtrain_CNN_blood_28.pth" , map_location=device))
adv_model.eval()
print("Adversarial-trained model loaded.")

feature_projector = nn.Linear(128, 10)

import torch.nn.functional as F

features_train = []

adv_model.eval()  # Set model to evaluation mode

for data, target in train_loader:
        data = data.to(device)
        # Forward pass to extract features
        out1, output =adv_model(data)  # Replace with the desired layer
        # Move feature_projector to the same device as the output
        feature_projector = feature_projector.to(device)  # Add this line
        output = feature_projector(output)
        print(output.shape)
        features_train.append(output.cpu())
        #labels.append(target.cpu())

# Concatenate all features and labels
features_train = torch.cat(features_train, dim=0)
#labels = torch.cat(labels, dim=0)

features_test = []

adv_model.eval()  # Set model to evaluation mode

for data, target in test_loader:
        data = data.to(device)
        # Forward pass to extract features
        out1, output =adv_model(data)  # Replace with the desired layer
        feature_projector = feature_projector.to(device)  # Add this line
        output = feature_projector(output)
        features_test.append(output.cpu())
        #labels.append(target.cpu())

# Concatenate all features and labels
features_test = torch.cat(features_test, dim=0)
#labels = torch.cat(labels, dim=0)
print(features_test.shape)

class CustomDatasetWithFeature(torch.utils.data.Dataset):
    def __init__(self, base_dataset, extra_features):
        """
        Args:
            base_dataset: The original dataset (e.g., train_dataset or test_dataset).
            extra_feature_func: A function that generates or provides extra features for the data.
        """
        self.base_dataset = base_dataset
        self.extra_features = extra_features

    def __len__(self):
        return len(self.base_dataset)

    def __getitem__(self, idx):
        # Get original data and target
        data, target, hogfeature = self.base_dataset[idx]

        # Generate or retrieve the extra feature
        extra_feature = self.extra_features[idx]

        # Return data, extra feature, and target
        return data, target, hogfeature, extra_feature

# Wrap datasets
train_dataset_with_feature = CustomDatasetWithFeature(train_loader_with_hog.dataset, features_train )
test_dataset_with_feature = CustomDatasetWithFeature(test_loader_with_hog.dataset, features_test)

# Create new DataLoaders
train_loader_with_feature = torch.utils.data.DataLoader(train_dataset_with_feature, batch_size = 128, shuffle=True)
test_loader_with_feature = torch.utils.data.DataLoader(test_dataset_with_feature, batch_size=128, shuffle=False)

for data, target, hogfeature, extra_feature in train_loader_with_feature:
    print("Data shape:", data.shape)

    print("Target shape:", target.shape)
    print("hog shape:", hogfeature.shape)
    print("Extra feature shape:", extra_feature.shape)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device: ", device, f"({torch.cuda.get_device_name(device)})" if torch.cuda.is_available() else "")

transformer = VisionTransformer(d_model,  vit_width, n_classes, img_size, patch_size, n_channels, n_heads, n_layers, emb_dim).to(device)

optimizer = Adam(transformer.parameters(), lr=alpha)
criterion = nn.CrossEntropyLoss()


# for epoch in range(100):

#   training_loss = 0.0
#   for i, data in enumerate(train_loader_with_feature, 0):
#     inputs, labels, feature_hog, feature_adv = data
#     inputs, labels, feature_hog, feature_adv = inputs.to(device), labels.to(device), feature_adv.to(device), feature_hog.to(device)

#     optimizer.zero_grad()

#     outputs = transformer(inputs, feature_adv, feature_hog)
#     labels = labels.reshape(-1)
#     loss = criterion(outputs, labels)
#     loss.backward(retain_graph=True)
#     optimizer.step()

#     training_loss += loss.item()

#   print(f'Epoch {epoch + 1}/{epochs} loss: {training_loss  / len(train_loader) :.3f}')

"""# Testing"""

#transformer = Net().to(device)
transformer.load_state_dict(torch.load("/content/drive/MyDrive/Research_workarea/blood_28_hog+adv.pth" , map_location=device))
transformer.eval()
print("Transformer loaded.")

# def save_model_to_drive(model, filename):
#     save_path = f"/content/drive/MyDrive/Research_workarea/{filename}"
#     torch.save(model.state_dict(), save_path)
#     print(f"Model saved to Google Drive as {save_path}")

# save_model_to_drive(transformer, "breast_28_hog+adv.pth")

def calculate_hog_features(images, orientations=9, pixels_per_cell=(8, 8), cells_per_block=(2, 2), block_norm='L2-Hys'):
    """
    Calculate HOG features for a set of images.

    Parameters:
        images (torch.Tensor or np.ndarray): A batch of images with shape (batch_size, height, width, channels) or (batch_size, channels, height, width).
        orientations (int): Number of orientation bins for HOG.
        pixels_per_cell (tuple): Size (in pixels) of a cell.
        cells_per_block (tuple): Number of cells per block.
        block_norm (str): Block normalization method.

    Returns:
        np.ndarray: HOG features for all images, shape (batch_size, hog_feature_size).
    """
    if isinstance(images, torch.Tensor):
        images = images.detach().permute(0, 2, 3, 1).numpy()  # Convert to (batch_size, height, width, channels)

    hog_features = []
    for img in images:
        # Convert to grayscale if necessary
        if img.shape[-1] == 3:  # Check if the image has 3 channels
            gray_img = rgb2gray(img)
        else:
            gray_img = img.squeeze()  # For single-channel images

        # Calculate HOG features
        features = hog(
            gray_img,
            orientations=orientations,
            pixels_per_cell=pixels_per_cell,
            cells_per_block=cells_per_block,
            block_norm=block_norm,
            visualize=False
        )
        hog_features_tensor = torch.tensor(features, dtype=torch.float32)
        hog_features_tensor = feature_projector_hog(hog_features_tensor)
        hog_features.append(hog_features_tensor.detach().numpy()) # Detach the tensor before converting to NumPy

    return np.array(hog_features)

# Function to calculate accuracy
def calculate_combined_accuracy(loader, model, device):
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels, hog_features, adv_features in loader:
            images, labels, hog_features, adv_features = images.to(device), labels.to(device), hog_features.to(device), adv_features.to(device)
            outputs = model(images, hog_features, adv_features)
            #print("outputs", outputs)
            #print("outputs.shape", outputs.shape)
            _, predicted = torch.max(outputs, 1)
            #print("predicted", predicted)
            # print("predicted.shape", predicted.shape)
            # print("labels", labels)
            # print("labels.shape", labels.shape)
            #print(labels.size(0))
            total += labels.size(0)
            #print(total)
            labels = labels.reshape(-1)
            #print("labels after", labels)
            correct += (predicted == labels).sum().item()
    return 100 * correct / total

acc_clean = calculate_combined_accuracy(test_loader_with_feature, transformer, device)
print(acc_clean)

# Adversarial attack (FGSM example)
def fgsm_attack_combined(images, epsilon, data_grad_images):
    # Perturb images
    feature_projector = nn.Linear(128, 10)
    perturbed_images = images + epsilon * data_grad_images.sign()
    perturbed_images = torch.clamp(perturbed_images, 0, 1)  # Keep pixel values valid
    print(perturbed_images.shape)
    # Perturb HOG features
    perturbed_hog_features = calculate_hog_features(perturbed_images)
    print(perturbed_hog_features.shape)
    perturbed_hog_features = torch.tensor(perturbed_hog_features, device=images.device, dtype=torch.float32)
    out1, output =adv_model(perturbed_images)  # Replace with the desired layer
    feature_projector = feature_projector.to(device)  # Add this line
    feat_adv = feature_projector(output)
    # gray_img = rgb2gray(perturbed_images.detach().cpu().numpy())
    # # Compute HOG features
    # perturbed_hog_features = hog(gray_img,
    #                        orientations=9,
    #                        pixels_per_cell=(8, 8),
    #                        cells_per_block=(2, 2),
    #                        block_norm='L2-Hys',
    #                        visualize=False)
    return perturbed_images, perturbed_hog_features, feat_adv

# Evaluate before and after adversarial attack
def evaluate_combined_with_attack(test_loader, model, device, epsilon):
    model.eval()
    correct_before = 0
    correct_after = 0
    total = 0

    criterion = nn.CrossEntropyLoss()

    for images, labels, hog_features, adv_features in test_loader:
        images, labels, hog_features, adv_features = (
            images.to(device),
            labels.to(device),
            hog_features.to(device),
            adv_features.to(device)
        )

        images.requires_grad = True
        #hog_features.requires_grad = True

        # Forward pass
        outputs = model(images, hog_features, adv_features)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        labels = labels.reshape(-1)
        correct_before += (predicted == labels).sum().item()

        # Calculate loss

        loss = criterion(outputs, labels)

        # Backward pass to compute gradients
        model.zero_grad()
        loss.backward(retain_graph=True) # Retain the graph for the adversarial attack calculation
        data_grad_images = images.grad.data
        #data_grad_hog = hog_features.grad.data

        # Apply FGSM attack
        perturbed_images, perturbed_hog_features, perturbed_adv_features = fgsm_attack_combined(
            images, epsilon, data_grad_images
        )
        #print("perturbed_hog_features.shape", perturbed_hog_features.shape)
        # Recalculate accuracy with perturbed features
        outputs_perturbed = model(perturbed_images, perturbed_hog_features, perturbed_adv_features)
        _, predicted_after = torch.max(outputs_perturbed, 1)
        #print("predicted_after", predicted_after)
        #print("labels", labels)
        correct_after += (predicted_after == labels).sum().item()

        if total == 128:
          break

    accuracy_before = 100 * correct_before / total
    accuracy_after = 100 * correct_after / total
    return accuracy_before, accuracy_after

# Example Usage
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
epsilon=0.1
# Assuming `test_loader_with_hog` is the DataLoader with images and HOG features
accuracy_before, accuracy_after = evaluate_combined_with_attack(
    test_loader_with_feature, transformer, device, epsilon
)

print(f"Accuracy before attack: {accuracy_before:.2f}%")
print(f"Accuracy after attack: {accuracy_after:.2f}%")

# Define epsilon values with step 0.05
epsilon_values = [i * 0.05 for i in range(1, 22)]  # 0.05, 0.1, ..., 0.5

# Loop over epsilon values
for epsilon in epsilon_values:
    print(f"Testing with epsilon = {epsilon:.2f}")
    # Assuming the necessary variables like transformer and device are defined
    accuracy_before, accuracy_after = evaluate_combined_with_attack(
        test_loader_with_feature, transformer, device, epsilon
    )
    print(f"Accuracy before attack: {accuracy_before:.2f}")
    print(f"Accuracy after attack: {accuracy_after:.2f}")

def pgd_attack(model, images, labels, epsilon, alpha, steps, device):
    feature_projector = nn.Linear(128, 10).to(device) # Move feature_projector to device here
    # Clone the original images to start the attack
    adv_images = images.clone().detach().to(device).requires_grad_(True)
    labels = labels.to(device)
    features = calculate_hog_features(adv_images)
    features = torch.tensor(features, device=device)

    with torch.enable_grad(): # Enable gradient calculation within the loop
        for _ in range(steps):
            adv_images.requires_grad = True
            out1, output =adv_model(adv_images)  # Replace with the desired layer
            feat_adv = feature_projector(output) # Calculate feat_adv inside the loop

            outputs = model(adv_images, features, feat_adv)
            loss = torch.nn.CrossEntropyLoss()(outputs, labels)
            loss.backward(retain_graph=True) # Retain the graph for subsequent iterations

            # Update adversarial images
            adv_images = adv_images + alpha * adv_images.grad.sign()
            adv_images = torch.clamp(adv_images, 0, 1)  # Ensure pixels are valid
            perturbation = torch.clamp(adv_images - images, -epsilon, epsilon)
            adv_images = torch.clamp(images + perturbation, 0, 1).detach()  # Apply perturbation

    return adv_images, features, feat_adv

def bim_attack(model, images, labels, epsilon, alpha, steps, device):
    # BIM is similar to PGD without the random start
    return pgd_attack(model, images, labels, epsilon, alpha, steps, device)

def cw_attack(model, images, labels, c, lr, steps, device):
    feature_projector = nn.Linear(128, 10).to(device) # initialize the feature projector on the GPU
    adv_images = images.clone().detach().to(device).requires_grad_(True)
    labels = labels.to(device)
    optimizer = torch.optim.Adam([adv_images], lr=lr)

    for _ in range(steps):
        adv_images.requires_grad = True
        features = calculate_hog_features(adv_images)
        features = torch.tensor(features, device=device)
        out1, output =adv_model(adv_images)  # Replace with the desired layer
        #feature_projector = feature_projector.to(device)  # Add this line
        feat_adv = feature_projector(output)

        outputs = model(adv_images, features, feat_adv)
        one_hot_labels = torch.eye(outputs.shape[1])[labels].to(device)

        # Compute Carlini-Wagner loss
        real = (one_hot_labels * outputs).sum(1)
        other = ((1 - one_hot_labels) * outputs - one_hot_labels * 1e4).max(1)[0]
        cw_loss = torch.clamp(other - real, min=-1).sum()

        # L2 loss to ensure perturbations are minimal
        l2_loss = torch.norm(adv_images - images, p=2)

        # Total loss
        loss = cw_loss + c * l2_loss

        # Update adversarial images
        optimizer.zero_grad() # clear previous gradient
        loss.backward() # calculate gradient
        optimizer.step() # update images based on gradients

        # Clamp images to ensure valid pixel range
        adv_images = torch.clamp(adv_images, 0, 1).detach().requires_grad_(True)

    return adv_images, features, feat_adv

def evaluate_attacks(test_loader, model, device, transformer, attack_fn, **attack_params):
    model.eval()
    correct = 0
    total = 0

    for images, labels, features, feat_adv in test_loader:
        # Move to device
        images = images.to(device)
        labels = labels.to(device)
        labels = labels.reshape(-1)
        # features = features.to(device)  # No need to move original features


        # Generate adversarial examples
        adv_images, features, features_adv = attack_fn(model, images, labels, device=device, **attack_params)

        # Evaluate the model on adversarial examples
        outputs = model(adv_images, features, features_adv)
        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

        if total == 384:
          break

    # Compute accuracy
    return correct / total

# Define attack parameters
epsilon = 0.1
alpha = 2 / 255
steps = 40
c = 1e-4
lr = 0.01
cw_steps = 100

# Evaluate PGD
pgd_accuracy = evaluate_attacks(
    test_loader_with_feature,
    transformer,
    device,
    transformer,
    pgd_attack,
    epsilon=epsilon,
    alpha=alpha,
    steps=steps,
)
print(f"PGD Attack Accuracy: {pgd_accuracy * 100:.2f}%")

# Evaluate BIM
bim_accuracy = evaluate_attacks(
    test_loader_with_feature,
    transformer,
    device,
    transformer,
    bim_attack,
    epsilon=epsilon,
    alpha=alpha,
    steps=steps,
)
print(f"BIM Attack Accuracy: {bim_accuracy * 100:.2f}%")

# Evaluate C&W
cw_accuracy = evaluate_attacks(
    test_loader_with_feature,
    transformer,
    device,
    transformer,
    cw_attack,
    c=c,
    lr=lr,
    steps=cw_steps,
)
print(f"C&W Attack Accuracy: {cw_accuracy * 100:.2f}%")

def run_attacks_with_varying_params(test_loader, model, transformer, device):
    # Define parameter grids for each attack
    pgd_params = {
        "epsilon": [i * 0.05 for i in range(1, 22)],
        "alpha": [1/255, 2/255, 4/255],
        "steps": [20, 40, 60],
    }

    bim_params = {
        "epsilon": [i * 0.05 for i in range(1, 22)],
        "alpha": [1/255, 2/255],
        "steps": [10, 20],
    }

    cw_params = {
        "c": [1e-4, 1e-3],
        "lr": [0.01, 0.001],
        "steps": [50, 100],
    }

    # Results storage
    results = []

    def evaluate_and_log(attack_name, params, attack_fn):
        print(f"\nRunning {attack_name} with parameters: {params}")
        accuracy = evaluate_attacks(
            test_loader,
            model,
            device,
            transformer,
            attack_fn,
            **params,
        )
        print(f"{attack_name} Accuracy: {accuracy * 100:.2f}%")
        results.append({"attack": attack_name, "params": params, "accuracy": accuracy})

    # Run PGD
    for epsilon in pgd_params["epsilon"]:
        for alpha in pgd_params["alpha"]:
            for steps in pgd_params["steps"]:
                params = {"epsilon": epsilon, "alpha": alpha, "steps": steps}
                evaluate_and_log("PGD", params, pgd_attack)

    # Run BIM
    for epsilon in bim_params["epsilon"]:
        for alpha in bim_params["alpha"]:
            for steps in bim_params["steps"]:
                params = {"epsilon": epsilon, "alpha": alpha, "steps": steps}
                evaluate_and_log("BIM", params, bim_attack)

    # Run C&W
    for c in cw_params["c"]:
        for lr in cw_params["lr"]:
            for steps in cw_params["steps"]:
                params = {"c": c, "lr": lr, "steps": steps}
                evaluate_and_log("C&W", params, cw_attack)

    return results

# Run attacks with varying parameters and collect results
results = run_attacks_with_varying_params(test_loader_with_feature, transformer, transformer, device)

# Display results
print("\nSummary of Results:")
for result in results:
    print(f"Attack: {result['attack']}, Params: {result['params']}, Accuracy: {result['accuracy'] * 100:.2f}%")